
package com.vidyo.webservices.content;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VidyoReplayContentManagementServicePortType", targetNamespace = "http://replay.vidyo.com/apiservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VidyoReplayContentManagementServicePortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.webservices.content.RecordsSearchResponse
     * @throws GeneralFault_Exception
     */
    @WebMethod(operationName = "RecordsSearch", action = "RecordsSearch")
    @WebResult(name = "RecordsSearchResponse", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
    public RecordsSearchResponse recordsSearch(
        @WebParam(name = "RecordsSearchRequest", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
        RecordsSearchRequest parameter)
        throws GeneralFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.webservices.content.RecordsResponse
     * @throws GeneralFault_Exception
     */
    @WebMethod(operationName = "RecordsById", action = "RecordsById")
    @WebResult(name = "RecordsResponse", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
    public RecordsResponse recordsById(
        @WebParam(name = "RecordsByIdRequest", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
        RecordsByIdRequest parameter)
        throws GeneralFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.webservices.content.UpdateRecordResponse
     * @throws GeneralFault_Exception
     * @throws AccessViolationFault_Exception
     */
    @WebMethod(operationName = "UpdateRecord", action = "UpdateRecord")
    @WebResult(name = "UpdateRecordResponse", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
    public UpdateRecordResponse updateRecord(
        @WebParam(name = "UpdateRecordRequest", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
        UpdateRecordRequest parameter)
        throws AccessViolationFault_Exception, GeneralFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.webservices.content.DeleteRecordResponse
     * @throws GeneralFault_Exception
     * @throws AccessViolationFault_Exception
     */
    @WebMethod(operationName = "DeleteRecord", action = "DeleteRecord")
    @WebResult(name = "DeleteRecordResponse", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
    public DeleteRecordResponse deleteRecord(
        @WebParam(name = "DeleteRecordRequest", targetNamespace = "http://replay.vidyo.com/apiservice", partName = "parameter")
        DeleteRecordRequest parameter)
        throws AccessViolationFault_Exception, GeneralFault_Exception
    ;

}
